// <auto-generated />
using System;
using System.Collections.Generic;
using Liro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Liro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LiroDbContext))]
    [Migration("20261009232031_AddItemMarketplaceUrl")]
    partial class AddItemMarketplaceUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Liro.Domain.Catalog.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AssetTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CollectibleItemId")
                        .HasColumnType("uuid");

                    b.Property<long?>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatorName")
                        .HasColumnType("text");

                    b.Property<string>("CreatorType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MarketplaceUrl")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("'https://www.roblox.com/catalog/' || \"RobloxAssetId\"::text", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("NextRefreshAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Restrictions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<long>("RobloxAssetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RobloxCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RobloxUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ThumbnailUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CollectibleItemId")
                        .IsUnique();

                    b.HasIndex("NextRefreshAt");

                    b.HasIndex("RobloxAssetId")
                        .IsUnique();

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Liro.Domain.Catalog.Entities.ItemMarketSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Data", "Liro.Domain.Catalog.Entities.ItemMarketSnapshot.Data#ItemMarketData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long?>("FavoriteCount")
                                .HasColumnType("bigint");

                            b1.Property<bool?>("HasResellers")
                                .HasColumnType("boolean");

                            b1.Property<bool?>("IsOffSale")
                                .HasColumnType("boolean");

                            b1.Property<bool?>("IsResellable")
                                .HasColumnType("boolean");

                            b1.Property<long?>("LowestPriceRobux")
                                .HasColumnType("bigint");

                            b1.Property<long?>("LowestResalePriceRobux")
                                .HasColumnType("bigint");

                            b1.Property<long?>("PriceBeforeDiscountRobux")
                                .HasColumnType("bigint");

                            b1.Property<string>("PriceStatus")
                                .HasColumnType("text");

                            b1.Property<long?>("PrimaryPriceRobux")
                                .HasColumnType("bigint");

                            b1.Property<long?>("TotalQuantity")
                                .HasColumnType("bigint");

                            b1.Property<long?>("UnitsAvailableForConsumption")
                                .HasColumnType("bigint");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "ObservedAtUtc")
                        .IsUnique();

                    b.ToTable("ItemMarketSnapshots", (string)null);
                });

            modelBuilder.Entity("Liro.Domain.Catalog.Entities.ItemMarketState", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Data", "Liro.Domain.Catalog.Entities.ItemMarketState.Data#ItemMarketData", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long?>("FavoriteCount")
                                .HasColumnType("bigint");

                            b1.Property<bool?>("HasResellers")
                                .HasColumnType("boolean");

                            b1.Property<bool?>("IsOffSale")
                                .HasColumnType("boolean");

                            b1.Property<bool?>("IsResellable")
                                .HasColumnType("boolean");

                            b1.Property<long?>("LowestPriceRobux")
                                .HasColumnType("bigint");

                            b1.Property<long?>("LowestResalePriceRobux")
                                .HasColumnType("bigint");

                            b1.Property<long?>("PriceBeforeDiscountRobux")
                                .HasColumnType("bigint");

                            b1.Property<string>("PriceStatus")
                                .HasColumnType("text");

                            b1.Property<long?>("PrimaryPriceRobux")
                                .HasColumnType("bigint");

                            b1.Property<long?>("TotalQuantity")
                                .HasColumnType("bigint");

                            b1.Property<long?>("UnitsAvailableForConsumption")
                                .HasColumnType("bigint");
                        });

                    b.HasKey("ItemId");

                    b.ToTable("ItemMarketState", (string)null);
                });

            modelBuilder.Entity("Liro.Infrastructure.Persistence.CatalogCheckpointState", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<string>("Cursor")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Scope");

                    b.ToTable("CatalogCheckpoints", (string)null);
                });

            modelBuilder.Entity("Liro.Infrastructure.Persistence.CatalogImportFailure", b =>
                {
                    b.Property<long>("AssetId")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssetId");

                    b.HasIndex("NextAttemptAtUtc")
                        .HasFilter("\"DeadLetteredAtUtc\" IS NULL");

                    b.ToTable("CatalogImportFailures", (string)null);
                });

            modelBuilder.Entity("Liro.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAtUtc", "OccurredAtUtc")
                        .HasFilter("\"ProcessedAtUtc\" IS NULL AND \"DeadLetteredAtUtc\" IS NULL");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Liro.Domain.Catalog.Entities.ItemMarketSnapshot", b =>
                {
                    b.HasOne("Liro.Domain.Catalog.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Liro.Domain.Catalog.Entities.ItemMarketState", b =>
                {
                    b.HasOne("Liro.Domain.Catalog.Entities.Item", null)
                        .WithOne("MarketState")
                        .HasForeignKey("Liro.Domain.Catalog.Entities.ItemMarketState", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Liro.Domain.Catalog.Entities.Item", b =>
                {
                    b.Navigation("MarketState");
                });
#pragma warning restore 612, 618
        }
    }
}
